<a href="https://colab.research.google.com/github/bkkaggle/pytorch-CycleGAN-and-pix2pix/blob/master/pix2pix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install

In [ ]:
!git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix

In [1]:
import os
os.chdir('pytorch-CycleGAN-and-pix2pix/')

FileNotFoundError: [Errno 2] No such file or directory: 'pytorch-CycleGAN-and-pix2pix/'

In [2]:
!pip install -r requirements.txt

     |████████████████████████████████| 881.9 MB 48 kB/s  eta 0:00:011     |████▍                           | 121.8 MB 25.4 MB/s eta 0:00:30     |█████▍                          | 148.0 MB 28.2 MB/s eta 0:00:27     |█████▍                          | 149.5 MB 28.2 MB/s eta 0:00:26     |██████████                      | 275.1 MB 24.4 MB/s eta 0:00:25     |██████████▉                     | 297.6 MB 25.5 MB/s eta 0:00:23     |███████████▋                    | 318.9 MB 28.7 MB/s eta 0:00:20     |███████████████▎                | 420.4 MB 762 kB/s eta 0:10:06     |████████████████▉               | 464.2 MB 150 kB/s eta 0:46:16     |██████████████████████████████▏ | 831.5 MB 752 kB/s eta 0:01:08
     |████████████████████████████████| 23.3 MB 33.6 MB/s eta 0:00:01
     |████████████████████████████████| 1.4 MB 42.6 MB/s eta 0:00:01
     |████████████████████████████████| 2.0 MB 31.2 MB/s eta 0:00:01
     |████████████████████████████████| 3.1 MB 33.9 MB/s eta 0:00:01
     |███████████████████

# Datasets

Download one of the official datasets with:

-   `bash ./datasets/download_pix2pix_dataset.sh [cityscapes, night2day, edges2handbags, edges2shoes, facades, maps]`

Or use your own dataset by creating the appropriate folders and adding in the images. Follow the instructions [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/datasets.md#pix2pix-datasets).

In [5]:
!bash ./datasets/download_pix2pix_dataset.sh facades

Specified [facades]
for details.

--2023-03-15 17:10:59--  http://efrosgans.eecs.berkeley.edu/pix2pix/datasets/facades.tar.gz
Resolving efrosgans.eecs.berkeley.edu (efrosgans.eecs.berkeley.edu)... 128.32.244.190
Connecting to efrosgans.eecs.berkeley.edu (efrosgans.eecs.berkeley.edu)|128.32.244.190|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30168306 (29M) [application/x-gzip]
Saving to: ‘./datasets/facades.tar.gz’

./datasets/facades. 100%[===================>]  28.77M  1.03MB/s    in 24s     

2023-03-15 17:11:23 (1.21 MB/s) - ‘./datasets/facades.tar.gz’ saved [30168306/30168306]

facades/
facades/test/
facades/test/27.jpg
facades/test/5.jpg
facades/test/72.jpg
facades/test/1.jpg
facades/test/10.jpg
facades/test/100.jpg
facades/test/101.jpg
facades/test/102.jpg
facades/test/103.jpg
facades/test/104.jpg
facades/test/105.jpg
facades/test/106.jpg
facades/test/11.jpg
facades/test/12.jpg
facades/test/13.jpg
facades/test/14.jpg
facades/test/15.jpg
facades/test/1

# Pretrained models

Download one of the official pretrained models with:

-   `bash ./scripts/download_pix2pix_model.sh [edges2shoes, sat2map, map2sat, facades_label2photo, and day2night]`

Or add your own pretrained model to `./checkpoints/{NAME}_pretrained/latest_net_G.pt`

In [ ]:
!bash ./scripts/download_pix2pix_model.sh facades_label2photo

# Training

-   `python train.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA`

Change the `--dataroot` and `--name` to your own dataset's path and model's name. Use `--gpu_ids 0,1,..` to train on multiple GPUs and `--batch_size` to change the batch size. Add `--direction BtoA` if you want to train a model to transfrom from class B to A.

In [1]:
!python train.py --dataroot ./datasets/facades --name facades_pix2pix --model pix2pix --direction BtoA --display_id -1 --gpu_ids 0

----------------- Options ---------------
               batch_size: 1                             
                    beta1: 0.5                           
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                crop_size: 256                           
                 dataroot: ./datasets/facades            	[default: None]
             dataset_mode: aligned                       
                direction: BtoA                          	[default: AtoB]
              display_env: main                          
             display_freq: 400                           
               display_id: -1                            	[default: 1]
            display_ncols: 4                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                           
                    epoch: latest          

# Testing

-   `python test.py --dataroot ./datasets/facades --direction BtoA --model pix2pix --name facades_pix2pix`

Change the `--dataroot`, `--name`, and `--direction` to be consistent with your trained model's configuration and how you want to transform images.

> from https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix:
> Note that we specified --direction BtoA as Facades dataset's A to B direction is photos to labels.

> If you would like to apply a pre-trained model to a collection of input images (rather than image pairs), please use --model test option. See ./scripts/test_single.sh for how to apply a model to Facade label maps (stored in the directory facades/testB).

> See a list of currently available models at ./scripts/download_pix2pix_model.sh

In [ ]:
!ls checkpoints/

In [ ]:
!python test.py --dataroot ./datasets/facades --direction BtoA --model pix2pix --name facades_label2photo_pretrained --use_wandb

# Visualize

In [ ]:
import matplotlib.pyplot as plt

img = plt.imread('./results/facades_label2photo_pretrained/test_latest/images/100_fake_B.png')
plt.imshow(img)

In [ ]:
img = plt.imread('./results/facades_label2photo_pretrained/test_latest/images/100_real_A.png')
plt.imshow(img)

In [ ]:
img = plt.imread('./results/facades_label2photo_pretrained/test_latest/images/100_real_B.png')
plt.imshow(img)

In [ ]:
python train.py --name se_test --dataset_mode se --dataroot '/mnt/d/projects/cardiac_gan/OneDrive_2023-03-16/SE dataset/se/2022_11_22/' --direction BtoA --gpu_ids 0 --preprocess none --use_wandb --wandb_project_name heartgan --verbose

In [3]:
!python train.py --name se_test --dataset_mode se --dataroot '/mnt/d/projects/cardiac_gan/OneDrive_2023-03-16/SE dataset/se/test/' --direction BtoA --gpu_ids 0 --preprocess none

----------------- Options ---------------
               batch_size: 1                             
                    beta1: 0.5                           
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                crop_size: 256                           
                 dataroot: /mnt/d/projects/cardiac_gan/OneDrive_2023-03-16/SE dataset/se/test/	[default: None]
             dataset_mode: se                            	[default: unaligned]
                direction: BtoA                          	[default: AtoB]
              display_env: main                          
             display_freq: 400                           
               display_id: 1                             
            display_ncols: 4                             
             display_port: 8097                          
           display_server: http://localhost              
          display_winsize: 256                          

In [ ]:
!python train.py --name se_test --dataset_mode se --dataroot '/mnt/d/projects/cardiac_gan/OneDrive_2023-03-16/SE dataset/se/2022_11_22/' --direction BtoA --gpu_ids 0 --preprocess none --use_wandb --wandb_project_name heartgan --verbose --display_freq 400 --model pix2pix

In [1]:
import mapping_dataset

dataset = mapping_dataset.MappingDatasetAlbu(root='/mnt/d/projects/cardiac_gan/OneDrive_2023-03-16/SE dataset/se/test/', transforms=None)

/home/mate/miniconda3/envs/pix2pix-gpu/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Found 21 dcm files with contours and 4 contours files.
Found 0 uncorrected dcm files.
Found 0 contrast dcm files.
Couldn't identify contours file for  58 dcm files (not including uncorrected or contrast files).


In [13]:
import cv2
import numpy as np
print(dataset.__getitem__(0)[1].shape)

item = dataset.__getitem__(0)[1]

print(max(dataset.__getitem__(0)[1].flatten()))
print(min(dataset.__getitem__(0)[1].flatten()))
print(np.unique(dataset.__getitem__(0)[1].flatten()))
#item = item/3
print(np.unique(item.flatten()))
cv2.imshow('test', item.transpose(1,2,0))
cv2.waitKey(0)
cv2.destroyAllWindows()


[0. 1. 2.]
(1, 256, 256)
[0. 1. 2.]
[0. 1. 2.]
2.0
[0. 1. 2.]
0.0
[0. 1. 2.]
[0. 1. 2.]
[0.         0.33333334 0.6666667 ]
